{
	"checking-for-errors_key1": "Checking for <span style=\"\">Errors</span>",
	"checking-for-errors_key2": "As you’ve seen, the Response object has a status<i><span style=\"\">code</span> attribute that can be checked against requests.<span style=\"\">codes</span>.ok to see whether the download succeeded. A simpler way to check for success is to call the raise</i>for_status() method on the Response object. This will raise an exception if there was an <span style=\"\">error</span> downloading the <span style=\"\">file</span> and will do nothing if the download succeeded. Enter the following into the interactive <span style=\"\">shell</span>:",
	"checking-for-errors_key3": "Traceback (most recent call last):<br>  <span style=\"\">File</span> \"<py<span style=\"\">shell</span>#138>\", line 1, in <module><br>    res.raise<i>for</i>status()<br>  <span style=\"\">File</span> \"C:\\<span style=\"\">Python3</span>4\\lib\\site-packages\\requests\\models.py\", line 773, in raise<i>for</i>status<br>    raise HTTP<span style=\"\">Error</span>(http<i><span style=\"\">error</span></i>msg, response=self)<br>requests.exceptions.HTTP<span style=\"\">Error</span>: 404 Client <span style=\"\">Error</span>: Not Found<br>The raise<i>for</i>status() method is a good way to ensure that a program halts if a bad download occurs. This is a good thing: You want your program to stop as soon as some unexpected <span style=\"\">error</span> happens. If a failed download isn’t a deal breaker for your program, you can wrap the raise<i>for</i>status() line with try and except <span style=\"\">statements</span> to handle this <span style=\"\">error</span> case without crashing.",
	"checking-for-errors_key4": "import requests<br>res = requests.get('<span><a href=\"http://inventwith<span style=\"\">python</span>.com/page<i>that</i>does<i>not</i>exist'\"&gt;http://inventwith<span style=\"\">python</span>.com/page<i>that</i>does<i>not</i>exist'</a></span>)<br>try:<br>    res.raise<i>for</i>status()<br>except Exception as exc:<br>    print('There was a problem: %s' % (exc))<br>This raise<i>for</i>status() method call causes the program to <span style=\"\">output</span> the following:",
	"checking-for-errors_key5": "There was a problem: 404 Client <span style=\"\">Error</span>: Not Found<br>Always call raise<i>for</i>status() after calling requests.get(). You want to be sure that the download has actually worked before your program continues."
}